version: 2
sources:
  - name: raw
    schema: gz_raw_data
    description: gz_raw_data_tables
    tables:
      - name : sales
        identifier : raw_gz_sales
        description: sales
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"

      - name : product
        identifier : raw_gz_product
        columns:
          - name: products_id
            tests:  
              - unique
              - not_null

      - name : ship
        identifier : raw_gz_ship
        columns:
          - name: orders_id
            tests:  
              - unique
              - not_null